name: Terraform Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_TERRAFORM }}

      - name: Export Azure credentials to environment variables
        run: |
          echo '${{ secrets.AZURE_CREDENTIALS_TERRAFORM }}' > azure-creds.json
          echo "ARM_CLIENT_ID=$(jq -r .clientId azure-creds.json)" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=$(jq -r .clientSecret azure-creds.json)" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=$(jq -r .subscriptionId azure-creds.json)" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=$(jq -r .tenantId azure-creds.json)" >> $GITHUB_ENV

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Bootstrap backend resources in Azure (if not exist)
        run: |
          az group show --name k8s-terraform || az group create --name k8s-terraform --location "westeurope"

          az storage account show --name terraformstateacc --resource-group k8s-terraform || \
          az storage account create --name terraformstateacc \
            --resource-group k8s-terraform \
            --location "westeurope" \
            --sku Standard_LRS \
            --encryption-services blob

          az storage container show --name terraform-state --account-name terraformstateacc || \
          az storage container create --name terraform-state \
            --account-name terraformstateacc

      - name: Get Storage Account Key
        run: |
          echo "STORAGE_KEY=$(az storage account keys list --resource-group k8s-terraform --account-name terraformstateacc --query '[0].value' -o tsv)" >> $GITHUB_ENV

      - name: Terraform Init with remote backend
        run: |
          terraform init \
            -backend-config="resource_group_name=k8s-terraform" \
            -backend-config="storage_account_name=terraformstateacc" \
            -backend-config="container_name=terraform-state" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="access_key=${{ env.STORAGE_KEY }}"

      - name: Terraform Apply (All resources)
        run: terraform apply -auto-approve
